### PR TITLE
User profile fields, Subjspec, & Borrowing Sidebar

### PR DESCRIPTION
**Pull request by Aurif3x**
https://zivtech.gitbooks.io/upenn-d8-pantheon-site/content/sprint_6_june_3_-_june_16.html

### CODE REVIEW

**Comment by Aurif3x** [comment]
I've re-enabled the staff profile fields and have re-done the "Languages" field as a Field Collection. Each item in the field collection contains a language (taxonomy reference) and a "Citation Only" boolean. With this arrangement, staff members can list as many languages as they want, and select whether each one is Citation Only or not. _Hopefully_ I've made all the necessary adjustments to this field's Solr/Facet configurations; it's kind of hard to tell at this point.

I've also submitted initial styling for the [borrowing pages' navigation sidebar](http://staffweb.library.upenn.edu/prototypes/cms/borrowing/borrowing-top-full.png). The Sass will get cleaner after we give the menu some classes. We also need to talk about gradients, vendor prefixes, and Autoprefixer.

**Comment by Aurif3x** [comment]
I've fixed the Subject Specialist page titles so that dashes no longer appear in them.
I still need to figure out how to get rid of ampersands and uppercase letters in the URLs. It looks like the uppercase letters might be a bug, because we've checked "Transform to lower case" and it's ignored: https://www.drupal.org/node/2645954

**Comment by Aurif3x** [comment]
## Subjspec: Dashes in Page Titles
I've fixed the Subject Specialist page titles so that dashes no longer appear in them.

## Subjspec: Ampersands in the URLs
I tried removing the ampersands with the suggested `replace` function: 
```
research/subject-specialists/{{ name_2 |lower|replace( {'-&amp;-': '-'} ) }}
```
This successfully changes the ending from 'Engineering-%26-Physical-Sciences' to 'engineering-physical-sciences'. However, this change breaks the contextual filter that relies on the URL ending to exactly match the taxonomy name, so the page title becomes 'Engineering Physical Sciences' and the list of specialists is empty.

## Subjspec: Uppercase letters in the URLs
It looks like this might be a bug: https://www.drupal.org/node/2645954
We've checked "Transform to lower case" and it's ignored; I've decided to implement the `lower` functionality from above to work around the issue. For some reason, `lower` converts the ampersand to "&amp;", so I've implemented this configuration to make sure the ampersand is properly escaped:
```
research/subject-specialists/{{ name_2 |lower|replace( {'&amp;': '%26'} ) }}
```
This means that for now, our final functional URL is at '/engineering-%26-physical-sciences'.

## Subjspec: "All" section
Ideally, the "All" section should be at '/library-info/subject-specialists' instead of '/library-info/subject-specialists/all'. However, my attempts at making this work have failed thus far.
We also still need to write some custom code to add the "All" tab to the top of the page.

**Comment by Aurif3x** [comment]
## Subjspec: "All" section
I've changed the view so that the "All" section lives at '/library-info/subject-specialists' instead of '/library-info/subject-specialists/all'.

We still need to write some custom code to add the "All" tab to the top of the page. When we do that, we should see if we can use that same code to add a `.active` class to the active tab.

**Comment by Aurif3x** [comment]
# User Field TODOs:
* **Subject Specialists:** Leslie's "Databases & Mockups" spreadsheet indicates that there needs to be a "Librarian Display Order" for subject specialties. She envisions that for each subject specialty selected, there is a dropdown where the user selects where they show up in the lists of librarians for that specialty ("First", "Second", ...). I don't know if this is actually possible with Views at all, much less whether it should be implemented like this or in some other manner.
* **Staff Directory Brief View:** The spreadsheet says there need to be checkboxes for "Show Library in Brief View" and "Show Division in Brief View". The intent is that these fields should only appear in the brief display mode if the boxes are selected. Again, I don't know if this is actually doable in Views or how to implement it. (I'm _guessing_ it could be done with some trickery using classes and possibly custom templates.)
* **Tools:** The spreadsheet lists a dropdown for "Tool Expertise Order". It suggests similar functionality to the aforementioned Subject Specialists Librarian Display Order: For each tool that is selected, there is a dropdown to pick where it appears in the list. Again, no idea about feasibility of implementation.
* **Offices:** We need to use a field collection instead of a text field. The field collection should contain a room (text field), a URL to the floor plan (or could we possibly delegate this to a taxonomy of possible floor plans?), and a phone number. This also eliminates the standalone "Phone" field.
* **Emergency Contact Responsibility:** This should be a field collection containing the type of emergency contact (dropdown: "Computer Lab Emergency", "Threat to Collections", "Website alert needed", etc), list order ("First", "Second", etc), and phone number. The phone number should contain both a number and a type (cell, home, pager), and multiple numbers should be allowed.
* **Photo visibility**: There needs to be a checkbox to allow the user to only show their picture to logged-in users. Assuming this is even possible with Field Permissions.
* **Various Responsibilities:** Liaison Responsibility, Collection Responsibility, Room Reservation Responsibility, Library Contact Responsibility, Circulation Contact Responsibility, Head of Circulation Contact Responsibility, Reserves Contact Responsibility, Reference Desk Responsibility, and ILL Contact Responsibility. These have stemmed from discussions where we would like to propagate staff information in other sections of the site; these should probably be dropdowns where we select appropriate areas of responsibility. We probably can't fully implement them until we have more of the site built out.
* **Show on Administration page, admin tab & libraries tab:** These are supposed to indicate whom the user reports to and appears under on each tab of the administration page.

It looks like a module like [Conditional Fields](https://www.drupal.org/project/conditional_fields) would be useful in a few cases, but I don't think anything like this has been ported to D8 yet.

**Comment by AllieRays** [comment]
merging into master for solr and core updates from pantheon to move down.

**Pull request merged**
